### PR TITLE
Adds 'insecure-tls' option to mservctl

### PR DESCRIPTION
**Pull request by excieve**

### CODE REVIEW

**Comment by excieve** [comment]
@jlucktay Not sure what you mean — `insecure-tls` flag being set means the option is set to `true` as it's `false` by default. So it is secure by default.

Same behaviour is in `curl`, `kubectl`, etc.

**Comment by jlucktay** [comment]
These are the godocs that confused me:

https://pkg.go.dev/crypto/tls?tab=doc

> // If InsecureSkipVerify is true, TLS accepts any certificate
> // presented by the server and any host name in that certificate.
> // In this mode, TLS is susceptible to man-in-the-middle attacks.
> // This should be used only for testing.
> InsecureSkipVerify bool

https://pkg.go.dev/github.com/go-openapi/runtime/client?tab=doc

> // InsecureSkipVerify controls whether the certificate chain and hostname presented
> // by the server are validated. If false, any certificate is accepted.
> InsecureSkipVerify bool

The [`httptransport` package](https://github.com/go-openapi/runtime/client) says `If false, any certificate is accepted.`
The stdlib `crypto/tls` package says `If InsecureSkipVerify is true, TLS accepts any certificate`.

Since we're using `httptransport` and its `TLSClientOptions` struct, then `false` sounds like the insecure option.
If we were using `crypto/tls` it would be the other way around, and `true` would be insecure.
Am I reading that right?

**Comment by excieve** [comment]
@jlucktay Fairly sure it's a typo in the openapi package docs. It behaves exactly as `crypto/tls` does (it's what it uses in the end). I've tested this and it behaves as expected: with flag set I'm able to connect to servers with self-signed certs, without the flag (default) I'm getting a TLS verification error.

**Comment by jlucktay** [comment]
OK, seems like a pretty sketchy typo to me though 😅

**Pull request merged**
